# Credentials for accessing the target WordPress instance
WordPress:
    # The XML-RPC API URL, typically your blog's base adress plus '/xmlrpc.php' ending
    xmlRcpApiUrl: https://example.com/xmlrpc.php
    # The username to post as (you should use an account with author privilege only)
    username: someuser
    # The password to the account
    password: monkey123
